name: Build LapisReplication

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Set up Gradle 9.1.0
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.1.0'

      - name: Build
        run: gradle build --stacktrace

      - name: Upload mod JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: LapisReplication-jar
          path: build/libs/*.jar
          if-no-files-found: error
